from os import environ

from pymongo import MongoClient, ReturnDocument

from swagger_server.models import Student

CONNECTION_STRING = environ.get('MONGO_URI', 'mongodb://localhost:27017')
client = MongoClient(CONNECTION_STRING)

def add(student: Student):
    if not student:
        return 'invalid input', 400

    # Check if the student already exists based on first and last name
    existing_student = client.students_db.students.find_one({
        'first_name': student.first_name,
        'last_name': student.last_name
    })

    if existing_student:
        return 'student already exists', 409

    # MongoDB makes use of strings as default. The specification wants to use
    # integers, so we need to generate our own IDs.
    # For ID generation, the user provided ID is always ignored, and a new ID
    # is generated by incrementing a counter in the database.
    next_id = client.students_db.counters.find_one_and_update(
        {'_id': 'student_id'},
        {'$inc': {'seq': 1}},
        upsert=True,
        return_document=ReturnDocument.AFTER
    )

    if not next_id:
        return 'error generating student ID', 500

    student.student_id = next_id['seq']
    client.students_db.students.insert_one({'_id': student.student_id, **student.to_dict()})

    return student.student_id


def get_by_id(student_id: int):
    student = client.students_db.students.find_one({'_id': student_id})
    if not student:
        return 'not found', 404
    student['student_id'] = student['_id']
    return student


def delete(student_id: int):
    student = client.students_db.students.find_one({'_id': student_id})
    if not student:
        return 'not found', 404
    client.students_db.students.delete_one({'_id': student_id})
    return student_id


def get_average_grade(student_id: int):
    student = client.students_db.students.find_one({'_id': student_id})
    if not student:
        return 'not found', 404
    grades = student.get('grade_records', [])
    if not grades:
        return 'no grades available', 404
    average = sum([grade['grade'] for grade in grades]) / len(grades)
    return average
